### ISSUE TITLE
Invisible selected entries

### ISSUE THREAD

**Issue by abhinandan1010** [FrederickRider/AutoCompleteBubbleText#5]
I am adding too much entries. After Adding new entry some time previous entries are invisible. Please suggest the solution on that...

**Comment by FrederickRider** [comment]
Hi, can you show me a clear example (with code) of what you mean?

I've realized that orientation change (rotating the phone) actually causes a lot of problems, and that might be the reason for your problem. I can fix it fast if you can give me an example of how you're using it :)

**Comment by abhinandan1010** [comment]
Solved the problem, Thanks

**Comment by ykulbashian** [comment]
Darn, any chance you could tell me how?
